spring:
  application:
    name: notification
  cloud:
#    function:
#      definition: orderCreated
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order.exchange
          content-type: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port:
    8084

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking