spring:
  application:
    name: order-service

  # h2:
  #   console:
  #     enabled: true
  # datasource:
  #   url: jdbc:h2:mem:test
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ${DB_USERNAME}
    
    password: ${DB_PASSWORD}

  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8081
